### ISSUE TITLE
First push to couchdb results in "Sorry, you must be logged in to save this presentation"

### ISSUE THREAD

**Issue by Tuxified** [quirkey/swinger#2]
Hi,

I just dowloaded swinger, tried to push it with couchapp, but halfway through it stopped and I got this message: File "build/bdist.linux-i686/egg/restkit/rest.py", line 488, in request
restkit.errors.Unauthorized: {"error":"forbidden","reason":"Sorry, you must be logged in to save this presentation"}

Obviously you have to make use of users to be able to use swinger, would be helpful to point at http://books.couchdb.org/relax/reference/security#Creating%20New%20Admin%20Users .

I've commented some lines in validate_doc_update.js, to get the initial presentations pushed to CouchDB, but it seems swinger really requires users to function properly :(

**Comment by quirkey** [comment]
Hey Tuxified

The code base is a little in flux right now as I've been updating it to support multiple users and the new CouchDB authentication features that are in CouchDB trunk (to be released for real soon). I think having at least one user set up named 'admin' will always have to be a requirement as I dont think theres a way to see if the couchdb instance has or doesnt have users via the validate function. I'll update the README accordingly soon.
