### ISSUE TITLE
Problems with push swinger (ubuntu 9.10, couchdb 0.10, couchapp 0.6.0)

### ISSUE THREAD

**Issue by abtris** [quirkey/swinger#3]
couchapp push . http://localhost:5984/slides
[INFO] Start request: GET http://localhost:5984
[INFO] Start request: HEAD http://localhost:5984/slides
[INFO] Start request: PUT http://localhost:5984/slides
[INFO] Start request: HEAD http://localhost:5984/slides/_design/swinger
[INFO] Start request: PUT http://localhost:5984/slides/_design/swinger
[INFO] Visit your CouchApp here:
http://localhost:5984/slides/_design/swinger/index.html
[INFO] Start request: GET http://localhost:5984
[INFO] Start request: HEAD http://localhost:5984/slides
[INFO] Start request: HEAD http://localhost:5984/slides/welcome
[INFO] Start request: POST http://localhost:5984/slides/_bulk_docs
[CRITICAL] global name 's' is not defined

Traceback (most recent call last):
  File "/home/prskavecl/src/couchapp/couchapp/dispatch.py", line 29, in dispatch
    return _dispatch(ui, args)
  File "/home/prskavecl/src/couchapp/couchapp/dispatch.py", line 75, in _dispatch
    return fun(ui, path, _args, *_opts)
  File "/home/prskavecl/src/couchapp/couchapp/commands.py", line 71, in push
    pushdocs(ui, docspath, dest, _args, *_opts)
  File "/home/prskavecl/src/couchapp/couchapp/commands.py", line 164, in pushdocs
    db.save_docs(docs1)
  File "/home/prskavecl/src/couchapp/couchapp/client.py", line 189, in save_docs
    errors.append(s)
NameError: global name 's' is not defined

**Comment by quirkey** [comment]
Hey abtris,

Unfortunately the current codebase requires CouchDB trunk (what will be CouchDB 0.11 - but isn't officially released yet) because the new couchdb authentication is only in trunk. Sorry! I'm updating the README with a warning/note

**Comment by abtris** [comment]
Today from trunks are all working
