### ISSUE TITLE
Branch sorting (ubuntu, couchdb 0.12.0ac4cd72b-git, swinger b0f17d9)

### ISSUE THREAD

**Issue by abtris** [quirkey/swinger#5]
Error in Edit Short ID (optional), nothing happend, only show undef error message.

info] [<0.1334.0>] 127.0.0.1 - - 'PUT' /swinger-sorting/git 500
[debug] [<0.1334.0>] httpd 500 error response:
 {"error":"unknown_error","reason":"undef"}

**Comment by quirkey** [comment]
Disable editing short id (actual doc id). Closed by 823aecec2d2305182965da99a8593633e5f26de9.

Unfortunately the way the system is set up now, the short id is actually === the id of the document, so it editing it would actually mean creating a new document.
